In [1]:
path_1 = '/Users/cu135/Downloads/master_list_v2.csv'
path_2 = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/memory_dbs/results/similarity_to_optimal/over65/bilateral/overlap-stimpyper_optimized_bilateral_vtas-stimpyper_clinician_bilateral_vtas.csv'

In [2]:
import pandas as pd
df1 = pd.read_csv(path_1)
df2 = pd.read_csv(path_2)
df2

,subject,Month_12_Delta_ADASMem,stimpyper_optimized_bilateral_vtas,stimpyper_clinician_bilateral_vtas,overlap_stimpyper_optimized_bilateral_vtas_vs_stimpyper_clinician_bilateral_vtas,Month_12_Delta_ADASMemImprove
0,102,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.151932,6
1,103,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.181780,4
2,106,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.288510,6
3,109,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.200547,6
4,110,3.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.175703,-3
5,113,-14.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.225215,11
6,114,-7.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.277243,7
7,116,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.212775,5
8,119,-1.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.169371,1
9,120,NaN,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.127523,0
10,121,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.159058,4
11,125,1.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.133862,-1
12,126,-7.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.305554,7
13,127,-1.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.122334,1
14,128,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.273711,6
15,129,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.143964,2
16,130,-7.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.245811,7
17,131,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.194383,0
18,133,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.247488,5
19,134,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.127472,0
20,138,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.300055,2
21,140,1.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.159681,-1
22,141,-20.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.308682,11
23,142,3.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.263035,-3
24,143,-3.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.262403,3
25,144,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.185527,5
26,145,2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.208501,-2
27,146,4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.091509,-4
28,149,2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.226914,-2
29,150,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.093623,8

In [3]:
df1['subject'].astype(str)
df2['subject'].astype(str)

0     102
1     103
2     106
3     109
4     110
5     113
6     114
7     116
8     119
9     120
10    121
11    125
12    126
13    127
14    128
15    129
16    130
17    131
18    133
19    134
20    138
21    140
22    141
23    142
24    143
25    144
26    145
27    146
28    149
29    150
Name: subject, dtype: object

In [4]:
merged_df = pd.merge(df1, df2, on='subject', how='outer')
merged_df

,cohort_key,stimulation_modality,subject_id,subject,delta_adasmem,percent_improvement_adas,age,baseline_adas,followup_adas,atrophy_path,...,data__yeo7__Limbic_FC,data__yeo7__Frontoparietal_A,data__yeo7__Frontoparietal_FC,data__yeo7__Default_A,data__yeo7__Default_FC,Month_12_Delta_ADASMem,stimpyper_optimized_bilateral_vtas,stimpyper_clinician_bilateral_vtas,overlap_stimpyper_optimized_bilateral_vtas_vs_stimpyper_clinician_bilateral_vtas,Month_12_Delta_ADASMemImprove
0,fornix_dbs,DBS,sub-101,101.0,NaN,-0.214286,62.0,28.0,34.0,files/fornix_dbs/sub-101/atrophy_path.nii.gz,...,14.435060,0.295749,-9.849473,0.485158,2.376464,NaN,NaN,NaN,NaN,NaN
1,fornix_dbs,DBS,sub-102,102.0,NaN,-0.363636,77.0,22.0,30.0,files/fornix_dbs/sub-102/atrophy_path.nii.gz,...,17.193963,0.408067,-10.334266,0.354756,3.755009,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.151932,6.0
2,fornix_dbs,DBS,sub-103,103.0,NaN,-0.789474,76.0,19.0,34.0,files/fornix_dbs/sub-103/atrophy_path.nii.gz,...,14.630112,0.359400,-9.882224,0.475581,4.449948,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.181780,4.0
3,fornix_dbs,DBS,sub-105,105.0,NaN,-0.105263,50.0,19.0,21.0,files/fornix_dbs/sub-105/atrophy_path.nii.gz,...,8.887128,0.216878,-3.358576,0.181887,0.902216,NaN,NaN,NaN,NaN,NaN
4,fornix_dbs,DBS,sub-106,106.0,NaN,-0.384615,66.0,13.0,18.0,files/fornix_dbs/sub-106/atrophy_path.nii.gz,...,14.001423,0.245907,-9.856519,0.280630,4.013440,-6.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,0.288510,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,bnm,DBS,Pat8,NaN,NaN,-11.111111,NaN,NaN,NaN,files/bnm/Pat8/atrophy_path.nii.gz,...,-0.493502,2.978483,-2.289092,4.717349,-3.710564,NaN,NaN,NaN,NaN,NaN
114,bnm,DBS,Pat9,NaN,NaN,17.500000,NaN,NaN,NaN,files/bnm/Pat9/atrophy_path.nii.gz,...,-0.676706,0.356289,-4.067742,0.315375,-3.146983,NaN,NaN,NaN,NaN,NaN
115,bnm,DBS,Pat4,NaN,NaN,8.330000,NaN,NaN,NaN,files/bnm/Pat4/atrophy_path.nii.gz,...,-0.399816,2.863390,-1.143710,3.405063,-4.107881,NaN,NaN,NaN,NaN,NaN
116,bnm,DBS,Pat10,NaN,NaN,33.330000,NaN,NaN,NaN,files/bnm/Pat10/atrophy_path.nii.gz,...,-1.000484,2.489321,0.048624,2.914052,-4.181682,NaN,NaN,NaN,NaN,NaN
117,bnm,DBS,Pat11,NaN,NaN,-25.000000,NaN,NaN,NaN,files/bnm/Pat11/atrophy_path.nii.gz,...,-0.002404,2.437744,-0.271703,2.994719,-3.648365,NaN,NaN,NaN,NaN,NaN

In [5]:
merged_df.to_csv('/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_and_stim/data/master_list_v2.csv', index=False)