# 00 - Import CSV with All Data - Optinal if you want to import with a CSV
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

Enter this information:

- import_path : str
    - The path to the directory containing the files to be imported or the path to a CSV file with file paths.
- subject_pattern : str, optional
    - A regular expression pattern indicating the part of the file path to be used as the subject ID.
- process_special_values : bool, optional
    - Whether to handle NaNs and infinities in the data without significantly biasing the distribution.
- file_column : str, optional
    - The name of the column in the CSV file that stores file paths (required if importing from CSV).
- file_pattern : str, optional
    - A file pattern to filter specific files in a folder (e.g., '*.nii.gz').

In [11]:
# Specify the path to your CSV file containing NIFTI paths
import_path = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_ReviewPyPer/metadata/master_list_ordinal_only.csv'
# File Column is the column name which has your paths in it
file_pattern = None #'roi_path'

Where do you want to save to?

In [12]:
# Specify where you want to save your results to
out_dir = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_ReviewPyPer/results/overlap_map'

Information on Master List CSV

In [13]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
cal_palm = CalvinStatsmodelsPalm(input_csv_path=import_path, output_dir=None, sheet=None)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,Subject,ses,LimbAtaxia,Gait,HeelToShinTest,Speech,Oculomotor,FingerToNoseTest,SematicFluencyRawS,PhonemicFluencyRawS,...,Sec4BIndifferent,Sec5AAngry,Sec5AUpset,Sec5AIntolerant,Sec5AArgumentative,Sec5Bimmature,Sec5BUnaware,Sec5BManner,Sec5BTrusting,Nifti_File_Path
0,sub-00136233,ses-16_Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
1,sub-00136233,ses-7__Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
2,sub-00317403,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
3,sub-00317403,ses-7__Ax_T1_3D_MPR_10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
4,sub-00467763,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,sub-8855431,ses-36_Loc,4.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
780,sub-8934864,ses-1001_Loc,4.0,2.0,2.0,2.0,2.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
781,sub-8945825,ses-1__Loc,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,NaN
782,sub-8999748,ses-1__Loc,4.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
783,sub-9018347,ses-5__Ax_T1_3D_MPRAGE_DL_W,3.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

Drop NaNs

In [14]:
data_df = cal_palm.drop_nans_from_columns("Nifti_File_Path")
data_df

,Subject,ses,LimbAtaxia,Gait,HeelToShinTest,Speech,Oculomotor,FingerToNoseTest,SematicFluencyRawS,PhonemicFluencyRawS,...,Sec4BIndifferent,Sec5AAngry,Sec5AUpset,Sec5AIntolerant,Sec5AArgumentative,Sec5Bimmature,Sec5BUnaware,Sec5BManner,Sec5BTrusting,Nifti_File_Path
0,sub-00136233,ses-16_Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
1,sub-00136233,ses-7__Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
2,sub-00317403,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
3,sub-00317403,ses-7__Ax_T1_3D_MPR_10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
4,sub-00467763,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,sub-4635137,ses-15_Ax_T1_Pre,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
494,sub-4635137,ses-16_Ax_T1_Pre,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
495,sub-4637200,ses-11_Sag_MPRAGE_W_PR_Tra_MPR,4.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
496,sub-4665593,ses-10_SZ_COR_T1_3D,4.0,2.0,2.0,1.0,2.0,2.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
497,sub-4685772,ses-2__Sag_T1_MEMPR_1mm_nomoco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...

Set the parameters for dropping rows

In [15]:
column = 'memory'  # The column you'd like to evaluate
condition = 'not'  # The condition to check ('equal', 'above', 'below', 'not')
value = 1 # The value to drop if found

In [16]:
# data_df, other_df = cal_palm.drop_rows_based_on_value(column, condition, value)
display(data_df)

,Subject,ses,LimbAtaxia,Gait,HeelToShinTest,Speech,Oculomotor,FingerToNoseTest,SematicFluencyRawS,PhonemicFluencyRawS,...,Sec4BIndifferent,Sec5AAngry,Sec5AUpset,Sec5AIntolerant,Sec5AArgumentative,Sec5Bimmature,Sec5BUnaware,Sec5BManner,Sec5BTrusting,Nifti_File_Path
0,sub-00136233,ses-16_Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
1,sub-00136233,ses-7__Ax_T1_MP_RAGE__MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
2,sub-00317403,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
3,sub-00317403,ses-7__Ax_T1_3D_MPR_10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
4,sub-00467763,ses-19_C__Ax_T1_3D__10_MPR_Sag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,sub-4635137,ses-15_Ax_T1_Pre,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
494,sub-4635137,ses-16_Ax_T1_Pre,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
495,sub-4637200,ses-11_Sag_MPRAGE_W_PR_Tra_MPR,4.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
496,sub-4665593,ses-10_SZ_COR_T1_3D,4.0,2.0,2.0,1.0,2.0,2.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...
497,sub-4685772,ses-2__Sag_T1_MEMPR_1mm_nomoco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy_R...

# 02 - Import Data - Can use CSV or import directly with globbed paths

In [17]:
nifti_col = 'Nifti_File_Path'

In [18]:
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
dv_df = GiiNiiFileImport(import_path=data_df[nifti_col], file_pattern=None, file_column=nifti_col, process_special_values=True,
                         mask_path=None).run()
dv_df

Attempting to import from pandas series. expecting PD series full of filenames. Will fail unless a series is provided using df["path_column"]

,-00136233/ses-16_Ax_T1_MP_RAGE__MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00136233_ses-16_Ax_T1_MP_RAGE__MPR_Sag_composite_s4.nii.gz,-00136233/ses-7__Ax_T1_MP_RAGE__MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00136233_ses-7__Ax_T1_MP_RAGE__MPR_Sag_composite_s4.nii.gz,-00317403/ses-19_C__Ax_T1_3D__10_MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00317403_ses-19_C__Ax_T1_3D__10_MPR_Sag_composite_s4.nii.gz,-00317403/ses-7__Ax_T1_3D_MPR_10_MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00317403_ses-7__Ax_T1_3D_MPR_10_MPR_Sag_composite_s4.nii.gz,-00467763/ses-19_C__Ax_T1_3D__10_MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00467763_ses-19_C__Ax_T1_3D__10_MPR_Sag_composite_s4.nii.gz,-00467763/ses-7__Ax_T1_3D_MPR_10_MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00467763_ses-7__Ax_T1_3D_MPR_10_MPR_Sag_composite_s4.nii.gz,-00572835/ses-16_Ax_T1_MP_RAGE__MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00572835_ses-16_Ax_T1_MP_RAGE__MPR_Sag_composite_s4.nii.gz,-00587497/ses-16_Ax_T1_MP_RAGE__MPR_Sag/unthresholded_tissue_segment_z_scores/sub-00587497_ses-16_Ax_T1_MP_RAGE__MPR_Sag_composite_s4.nii.gz,-00596243/ses-9__Ax_T1_MP_RAGE/unthresholded_tissue_segment_z_scores/sub-00596243_ses-9__Ax_T1_MP_RAGE_composite_s4.nii.gz,-00601200/ses-16_AX_T1FS_VIBE_3D/unthresholded_tissue_segment_z_scores/sub-00601200_ses-16_AX_T1FS_VIBE_3D_composite_s4.nii.gz,...,-46261541/ses-9__Ax_T1_3D_MPRAGE/unthresholded_tissue_segment_z_scores/sub-46261541_ses-9__Ax_T1_3D_MPRAGE_composite_s4.nii.gz,-4626645/ses-5__T1_MPRAGE_SAG/unthresholded_tissue_segment_z_scores/sub-4626645_ses-5__T1_MPRAGE_SAG_composite_s4.nii.gz,-4627076/ses-18_AXIAL_MPRAGE/unthresholded_tissue_segment_z_scores/sub-4627076_ses-18_AXIAL_MPRAGE_composite_s4.nii.gz,-4631537/ses-12_Bulter_Ax_T1_No_angle/unthresholded_tissue_segment_z_scores/sub-4631537_ses-12_Bulter_Ax_T1_No_angle_composite_s4.nii.gz,-4631615/ses-1__Loc/unthresholded_tissue_segment_z_scores/sub-4631615_ses-1__Loc_composite_s4.nii.gz,-4635137/ses-15_Ax_T1_Pre/unthresholded_tissue_segment_z_scores/sub-4635137_ses-15_Ax_T1_Pre_composite_s4.nii.gz,-4635137/ses-16_Ax_T1_Pre/unthresholded_tissue_segment_z_scores/sub-4635137_ses-16_Ax_T1_Pre_composite_s4.nii.gz,-4637200/ses-11_Sag_MPRAGE_W_PR_Tra_MPR/unthresholded_tissue_segment_z_scores/sub-4637200_ses-11_Sag_MPRAGE_W_PR_Tra_MPR_composite_s4.nii.gz,-4665593/ses-10_SZ_COR_T1_3D/unthresholded_tissue_segment_z_scores/sub-4665593_ses-10_SZ_COR_T1_3D_composite_s4.nii.gz,-4685772/ses-2__Sag_T1_MEMPR_1mm_nomoco/unthresholded_tissue_segment_z_scores/sub-4685772_ses-2__Sag_T1_MEMPR_1mm_nomoco_composite_s4.nii.gz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# 03 - Generate Sensitivity Map
- If generating map without a standard mask, use /nifti_procesing/02b_create_mask_combined.ipynb first.

In [20]:
mask_path = '/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/MNI152_T1_2mm_brain_mask.nii'

In [ ]:
from calvin_utils.neuroimaging_utils.ccm_utils.sensitivity_map import SensitivityMap

omap = SensitivityMap(
        mask_path=mask_path,
        df=dv_df.T,
        out_dir=out_dir,
        map_type='t',      # 'ROI', 't', 'r', 'rfz' or 'custom'
        manual_threshold=None,
        verbose=False
).run()

Average Map

In [21]:
mask_img.affine

array([[  -2.,    0.,    0.,   90.],
       [   0.,    2.,    0., -126.],
       [   0.,    0.,    2.,  -72.],
       [   0.,    0.,    0.,    1.]])

In [30]:
import nibabel as nib
import os
import numpy as np

avg = np.mean(dv_df.values, axis=1)
mask_img = nib.load(mask_path)
arr = np.reshape(avg, mask_img.get_fdata().shape)
img = nib.Nifti1Image(arr, affine=mask_img.affine)


os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, f'threshold_average_map.nii.gz')
nib.save(img, out_path)